Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "AutoMarket"
admin.site.index_title = "Admin panel"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("market/", include(("goods.urls", "goods"), namespace="goods")),
    path("cart/", include(("cart.urls", "cart"), namespace="cart")),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("", include("users.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>", add_to_shopping_cart, name="add_to_cart"),
    path("remove/<int:product_id>", remove_from_cart, name="remove_from_cart"),
    path("orders-history", OrdersHistory.as_view(), name="orders-history"),
    path("orders-history/<int:order_pk>", order_info, name="order"),
    path("orders-history/<int:pk>/remove/", RemoveOrder.as_view(), name="remove-order"),
]

goods/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", MarketPage.as_view(), name="market"),
    path("search", search, name="search"),
    path("create", create_product_card, name="create-card"),
    path("moderation", products_on_moderation, name="moderation"),
    path(
        "moderation/remove/<int:pk>",
        RemoveProductOnModeration.as_view(),
        name="moderation-remove",
    ),
    path(
        "moderation/approve/<int:pk>",
        ApproveProductModeration.as_view(),
        name="moderation-approve",
    ),
    path("<slug:slug_category>", category, name="category-detail"),
    path(
        "<slug:slug_category>/<int:product_id>",
        ProductCard.as_view(),
        name="product-card",
    ),
    path(
        "<slug:slug_category>/<slug:slug_subcategory>", category, name="category-detail"
    ),
]

cart/models.py
import json
from django.contrib.auth.models import User
from django.db import models

from goods.models import Product


CURRENCY_CHOICES = [
    ("EURO", "Euro"),
    ("USD", "Dollars"),
]

STATUS_CHOICES = [
    ("PLACE", "Placing"),
    ("OPEN", "Open"),
    ("CANCELED", "Canceled"),
    ("DELIVERED", "Delivered"),
]


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(null=True, max_length=40)
    address = models.CharField(null=True, max_length=60)
    postal_code = models.CharField(null=True, max_length=10)
    phone_number = models.CharField(null=True, max_length=10)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default="PLACE")
    comment = models.CharField(max_length=60, blank=True, null=True)
    currency = models.CharField(max_length=7, choices=CURRENCY_CHOICES, default="Euro")

    def order_cost(self):
        return sum(item.item_cost() for item in self.items.all())

    def status_message(self):
        if self.status == "PLACE":
            return "Fill in additional information to place an order"
        elif self.status == "OPEN":
            return "Awaiting delivery"
        elif self.status == "CANCELED":
            return "The order has been canceled"
        else:
            return "The order has been delivered"

    def get_html_class_for_table(self):
        if self.status == "PLACE":
            return "table-warning"
        elif self.status == "OPEN":
            return "table-light"
        elif self.status == "CANCELED":
            return "table-secondary"
        else:
            return "table-success"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="products", on_delete=models.PROTECT
    )
    amount = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def item_cost(self):
        return self.price * self.amount

cart/forms.py
from django import forms
from django.forms import NumberInput, TextInput, Textarea
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import *
import re
import datetime


AMOUNT_CHOICES = [(i, str(i)) for i in range(1, 21)]


class AddToCartForm(forms.Form):
    amount = forms.IntegerField(
        initial=1,
        validators=[MinValueValidator(1), MaxValueValidator(100)],
        widget=NumberInput(
            attrs={"class": "form-control form-control-sm", "style": "width:7ch;"}
        ),
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['amount'].disabled = True


payment_widgets = {
    "name": TextInput(
        attrs={
            "placeholder": "Cardholder's Name",
            "class": "form-select form-select-lg",
            "size": 17,
        }
    ),
    "card_number": TextInput(
        attrs={
            "placeholder": "1234 5678 9012 3457",
            "class": "form-select form-select-lg",
            "size": 17,
            "minlength": 19,
            "maxlength": 19,
        }
    ),
    "expiration": TextInput(
        attrs={
            "placeholder": "MM/YYYY",
            "class": "form-select form-select-lg",
            "size": 7,
            "minlength": 7,
            "maxlength": 7,
        }
    ),
    "cvv": TextInput(
        attrs={
            "placeholder": "999",
            "class": "form-select form-select-lg",
            "size": 1,
            "minlength": 3,
            "maxlength": 3,
            "type": "password",
        }
    ),
}


class PaymentForm(forms.Form):
    name = forms.CharField(widget=payment_widgets["name"])
    card_number = forms.IntegerField(widget=payment_widgets["card_number"])
    expiration = forms.CharField(widget=payment_widgets["expiration"])
    cvv = forms.IntegerField(widget=payment_widgets["cvv"])

    def clean_expiration(self):
        data = self.cleaned_data
        expiration = data["expiration"]
        if re.search("^((0[1-9])|(1[0-2]))/([0-9]{4})$", expiration):
            today = datetime.datetime.today()
            date = datetime.datetime.strptime(expiration, "%m/%Y")
            if today > date or date > today + datetime.timedelta(days=5500):
                raise forms.ValidationError("Invalid date")
            return expiration
        raise forms.ValidationError("Invalid input (try MM/YYYY)")


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("full_name", "address", "postal_code", "phone_number", "comment")
        widgets = {
            "full_name": TextInput(
                attrs={
                    "placeholder": "Full name",
                    "class": "form-control",
                }
            ),
            "address": TextInput(
                attrs={
                    "placeholder": "Street address. City.",
                    "class": "form-control",
                }
            ),
            "postal_code": NumberInput(
                attrs={
                    "placeholder": "123456",
                    "class": "form-control",
                    "minlength": 6,
                    "maxlength": 6,
                }
            ),
            "phone_number": TextInput(
                attrs={
                    "placeholder": "+1 123 4567890",
                    "class": "form-control",
                }
            ),
            "comment": Textarea(
                attrs={
                    "placeholder": "Comment for delivery",
                    "class": "form-control",
                    "rows": 5,
                }
            ),
        }

cart/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import *
from goods.models import Product
from .models import *


@require_POST
def add_to_shopping_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddToCartForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        cart.add_to_cart(
            product=product,
            amount=data["amount"],
            update_amount=data["amount"],
        )
    return redirect("cart:cart_detail")


@login_required
def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


@login_required
def cart_detail(request):
    cart = Cart(request)
    for product in cart:
        product["update_amount_form"] = AddToCartForm(
            initial={"amount": product["amount"], "update": True}
        )

    if "currency" in request.COOKIES:
        currency = request.COOKIES.get("currency")
    else:
        currency = "EURO"

    payment_form = PaymentForm(request.POST)
    error_message = ""
    if request.method == "POST" and payment_form.is_valid():
        if len(cart) > 0:
            order = Order.objects.create(
                user=request.user, status="PLACE", currency=currency
            )

            for item in cart:
                if item["product"].amount < item["amount"]:
                    amount = item["product"].amount
                else:
                    amount = item["amount"]
                item["product"].amount -= amount
                item["product"].save()

                if currency == "Euro":
                    price = item["price_euro"]
                else:
                    price = item["price_usd"]

                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    amount=amount,
                    price=price,
                )

            cart.clear()
            return redirect(reverse("cart:order", kwargs={"order_pk": order.pk}))
        error_message = "Cart is empty or product is not available"

    return render(
        request,
        "cart/ShoppingCart.html",
        context={
            "cart": cart,
            "currency": currency,
            "payment_form": payment_form,
            "error_message": error_message,
        },
    )


class OrdersHistory(LoginRequiredMixin, ListView):
    model = Order
    template_name = "cart/OrdersHistory.html"
    context_object_name = "orders"

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


@login_required()
def order_info(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    if order.user == request.user:
        items = order.items.all()
        data = request.POST
        order_form = OrderForm(data)

        if request.POST and order_form.is_valid() and order.status == "PLACE":
            order.full_name = data["full_name"]
            order.address = data["address"]
            order.postal_code = data["postal_code"]
            order.phone_number = data["phone_number"]
            if "comment" in data:
                order.comment = data["comment"]
            order.status = "OPEN"
            order.save()

        return render(
            request,
            "cart/Order.html",
            context={
                "order": order,
                "items": items,
                "order_form": order_form,
            },
        )
    return redirect("/")


class RemoveOrder(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy("cart:orders-history")

cart/templates/cart/Order.html
{% extends 'base.html' %}

{% block title %}Order {{order.pk}}{% endblock %}


{% block content %}
<section class="h-100 h-custom" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card">
          <div class="card-body p-4">
            <div class="row">
              <div class="col-lg-7">
                <div class="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <p class="mb-1">Order #{{order.pk}}</p>
                    <p class="mb-1">Status: {{order.status_message}}</p>
                  </div>
                  <div class="delete-order">
                    <form method="POST" action="{% url 'cart:remove-order' order.pk %}">
                      {% csrf_token %}<input class="btn btn-danger" type="submit" value="DELETE">
                    </form>
                  </div>
                </div>
                {% for item in items %}
                {% with item.product as product %}
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <div>
                          <img
                            src="{{ product.picture.url }}"
                            class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                        </div>
                        <div class="ms-3">
                          <h5>{{ product.name|truncatewords:5 }}</h5>
                            {% if order.currency == 'EURO' %}
                          <p class="small mb-0">{{ item.price }} €</p>
                            {% else %}
                          <p class="small mb-0">{{ item.price }} $</p>
                            {% endif %}
                        </div>
                      </div>
                      <div class="d-flex flex-row align-items-center">
                        <h4 >(x{{ item.amount }})</h4>
                        <div class="cart-price me-3 ms-2">
                            {% if order.currency == 'EURO' %}
                          <h5 class="mb-0"><nobr>{{ item.item_cost }} € </nobr></h5>
                            {% else %}
                          <h5 class="mb-0"><nobr>{{ item.item_cost }} $ </nobr></h5>
                            {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endwith %}
                {% endfor %}
              </div>
              <div class="col-lg-5">
                <div class="card bg-primary text-white rounded-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                      <h5 class="mb-0">Order details</h5>
                    </div>
                    {% if order.status == 'PLACE' %}
                    <form action="" method="post">
                      {% csrf_token %}
                      <div class="form-outline form-white mb-2">
                          {{ order_form.full_name }}
                          <label class="form-label">Full name</label>
                      </div>
                      <div class="form-outline form-white mb-2">
                          {{ order_form.address }}
                          <label class="form-label">Delivery address</label>
                      </div>
                      <div class="form-outline form-white mb-2">
                          {{ order_form.postal_code }}
                          <label class="form-label">Postal code</label>
                      </div>
                      <div class="form-outline form-white mb-2">
                          {{ order_form.phone_number }}
                          <label class="form-label">Phone number</label>
                      </div>
                      <div class="form-outline form-white mb-2">
                          {{ order_form.comment }}
                          <label class="form-label">Your comment</label>
                      </div>

                    <hr class="my-4">
                      <div class="d-flex justify-content-between mb-4">
                        <p class="mb-2">Total(Incl. taxes)</p>
                          {% if order.currency == 'EURO' %}
                            <p class="mb-2">{{ order.order_cost }} €</p>
                          {% else %}
                            <p class="mb-2">{{ order.order_cost }} $</p>
                          {% endif %}
                      </div>
                      <button type="submit" class="btn btn-info btn-block btn-lg">Place order</button>
                    </form>
                    {% else %}
                      <p class="mb-2">Full name: {{ order.full_name }} </p>
                      <p class="mb-2">Address: {{ order.address }} </p>
                      <p class="mb-2">Postal code: {{ order.postal_code }} </p>
                      <p class="mb-2">Phone number: {{ order.phone_number }} </p>
                      <p class="mb-2">Comment: {{ order.comment }} </p>
                      <p class="mb-2">Last change: {{ order.updated }} </p>
                      <hr class="my-4">
                        <div class="d-flex justify-content-between mb-4">
                          <p class="mb-2">Total(Incl. taxes)</p>
                            {% if order.currency == 'EURO' %}
                              <p class="mb-2">{{ order.order_cost }} €</p>
                            {% else %}
                              <p class="mb-2">{{ order.order_cost }} $</p>
                            {% endif %}
                        </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

cart/templates/cart/OrdersHistory.html
{% extends 'base.html' %}

{% block title %}Orders history{% endblock %}


{% block content %}
<section class="purchase-history">
  <div class="container py-5 h-100">
    <h1>Purchase history</h1>
      <table class='table' data-sort="table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Status</th>
            <th>Comment</th>
            <th>Date</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
          <tr class="{{ order.get_html_class_for_table }}">
            <td><a href="{% url 'cart:order' order.pk %}">#{{ order.pk }}</a></td>
            <td>{{ order.get_status_display }}</td>
            <td>{{ order.comment|linebreaks }}</td>
            <td><nobr>{{ order.created }}</nobr></td>
            {% if order.currency == 'EURO' %}
              <td><nobr>{{ order.order_cost }} €</nobr></td>
            {% else %}
              <td><nobr>{{ order.order_cost }} $</nobr></td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
</section>
{% endblock %}

cart/templates/cart/ShoppingCart.html
{% extends 'base.html' %}

{% block title %}Shopping cart{% endblock %}


{% block content %}
<section class="shopping-cart">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card">
          <div class="card-body p-4">
            <div class="row">
              <div class="col-lg-7">
                {% if user.profile.user_type == 'Customer'%}
                <h5 class="mb-3"><a href="{% url 'goods:market' %}" class="text-body"><i
                      class="fas fa-long-arrow-alt-left me-2"></i>Continue shopping</a></h5>
                <hr>

                <div class="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <p class="mb-1">Shopping cart</p>
                    {% with total_items=cart|length %}
                      {% if cart|length > 0 %}
                    <p class="mb-0">You have {{ total_items }} item{{ total_items|pluralize }} in your cart</p>
                      {% else %}
                    <p class="mb-0">Your cart is empty.</p>
                      {% endif %}
                      {% endwith %}
                    {% if error_message %}
                    <p class="mb-0">{{error_message}}</p>
                    {% endif %}
                  </div>

                </div>

                {% for item in cart %}
                {% with item.product as product %}
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <div class="product-img">
                          <img
                            src="{{ product.picture.url }}"
                            alt="Shopping item" width="65">
                        </div>
                        <div class="ms-3">
                          <h5>{{ product.name|truncatewords:5 }}</h5>
                            {% if currency == 'EURO' %}
                          <p class="small mb-0">{{ item.price_euro }} €</p>
                            {% else %}
                          <p class="small mb-0">{{ item.price_usd }} $</p>
                            {% endif %}
                        </div>
                      </div>
                      <div class="d-flex flex-row align-items-center">
                          <div class="width: 50px; add_to_cart_form">
                            <form class="d-flex justify-content-between align-items-center"
                                    action="{% url 'cart:add_to_cart' product.id %}" method="post">
                              {% csrf_token %}
                              <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                <i class="fas fa-minus"></i>
                              </button>
                              {{ item.update_amount_form.amount }}
                              <button class="btn btn-link px-2"
                                onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                <i class="fas fa-plus"></i>
                              </button>
                              {{ item.update_amount_form.update }}
                            </form>
                          </div>
                        <div class="cart-price me-3 ms-2">
                            {% if currency == 'EURO' %}
                          <h5 class="mb-0"><nobr>{{ item.total_price_euro }} € </nobr></h5>
                            {% else %}
                          <h5 class="mb-0"><nobr>{{ item.total_price_usd }} $ </nobr></h5>
                            {% endif %}
                        </div>
                        <a href="{% url 'cart:remove_from_cart' product.id %}" ><i class="fas fa-trash fa-lg"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endwith %}
                {% endfor %}

                {% else %}
                <div class="mb-0">Sellers can't make purchases.</div>
                {% endif %}
              </div>

              <div class="col-lg-5">

                <div class="card bg-primary text-white rounded-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                      <h5 class="mb-0">Card details</h5>
                    </div>

                    <p class="small mb-2">Card type</p>
                    <a href="#!" type="submit" class="text-white"><i
                        class="fab fa-cc-mastercard fa-2x me-2"></i></a>
                    <a href="#!" type="submit" class="text-white"><i
                        class="fab fa-cc-visa fa-2x me-2"></i></a>
                    <a href="#!" type="submit" class="text-white"><i class="fab fa-cc-paypal fa-2x"></i></a>


                    <form class="mt-4" action="{% url 'cart:cart_detail' %}" method="post" >
                        {% csrf_token %}
                        <div class="form-outline form-white mb-4">
                          {{ payment_form.name }}
                          <label class="form-label">Cardholder's Name</label>
                        </div>

                        <div class="form-outline form-white mb-4">
                          {{ payment_form.card_number }}
                          <label class="form-label">Card Number</label>
                        </div>

                        <div class="row mb-4">
                          <div class="col-md-6">
                            <div class="form-outline form-white errors">
                              {{ payment_form.expiration }}
                              {{ payment_form.expiration.errors }}
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-outline form-white">
                              {{ payment_form.cvv }}
                              <label class="form-label" >CVV</label>
                            </div>
                          </div>
                        </div>


                      <hr class="my-4">

                      <div class="d-flex justify-content-between mb-4">
                        <p class="mb-2">Total(Incl. taxes)</p>
                          {% if currency == 'EURO' %}
                            <p class="mb-2">{{ cart.get_total_price_euro }} €</p>
                          {% else %}
                            <p class="mb-2">{{ cart.get_total_price_usd }} $</p>
                          {% endif %}
                      </div>
                      <button type="submit" class="btn btn-info btn-block btn-lg">Checkout</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="https://kit.fontawesome.com/26fc0dada0.js" crossorigin="anonymous"></script>
{% endblock %}