Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "AutoMarket"
admin.site.index_title = "Admin panel"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("market/", include(("goods.urls", "goods"), namespace="goods")),
    path("cart/", include(("cart.urls", "cart"), namespace="cart")),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("", include("users.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>", add_to_shopping_cart, name="add_to_cart"),
    path("remove/<int:product_id>", remove_from_cart, name="remove_from_cart"),
    path("orders-history", OrdersHistory.as_view(), name="orders-history"),
    path("orders-history/<int:order_pk>", order_info, name="order"),
    path("orders-history/<int:pk>/remove/", RemoveOrder.as_view(), name="remove-order"),
]

feedback/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("create/<int:product_id>", add_feedback, name="add_feedback"),
    path("remove/<int:feedback_id>", remove_feedback, name="remove_feedback"),
]

goods/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", MarketPage.as_view(), name="market"),
    path("search", search, name="search"),
    path("create", create_product_card, name="create-card"),
    path("moderation", products_on_moderation, name="moderation"),
    path(
        "moderation/remove/<int:pk>",
        RemoveProductOnModeration.as_view(),
        name="moderation-remove",
    ),
    path(
        "moderation/approve/<int:pk>",
        ApproveProductModeration.as_view(),
        name="moderation-approve",
    ),
    path("<slug:slug_category>", category, name="category-detail"),
    path(
        "<slug:slug_category>/<int:product_id>",
        ProductCard.as_view(),
        name="product-card",
    ),
    path(
        "<slug:slug_category>/<slug:slug_subcategory>", category, name="category-detail"
    ),
]

goods/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg
from django.urls import reverse
from django.utils.text import slugify


def category_directory_path(instance, filename):
    return "uploads/categories_pictures/{0}".format(filename)


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(default="", db_index=True)
    picture = models.ImageField(
        upload_to=category_directory_path,
        verbose_name="Category Image",
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("goods:category-detail", args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(default="", db_index=True)
    category = models.ForeignKey(
        Category, related_name="subcategories", on_delete=models.PROTECT
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Subcategory, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "goods:category-detail",
            kwargs={
                "slug_category": self.category.slug,
                "slug_subcategory": self.slug,
            },
        )


class CurrencyRate(models.Model):
    Euro_to_Usd = models.DecimalField(max_digits=6, decimal_places=4)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = "updated"

    def save(self, *args, **kwargs):
        super(CurrencyRate, self).save(*args, **kwargs)
        all_products = Product.objects.all()
        for product in all_products:
            product.price_usd = product.price_euro * self.Euro_to_Usd
            product.save()


def user_directory_path(instance, filename):
    return "uploads/user_{0}/{1}".format(instance.user.id, filename)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.PROTECT
    )
    subcategory = models.ForeignKey(
        Subcategory, related_name="products", on_delete=models.PROTECT
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    part_number = models.CharField(max_length=30)
    discription = models.TextField()
    amount = models.PositiveIntegerField()
    price_euro = models.DecimalField(
        validators=[MinValueValidator(1)],
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )
    price_usd = models.DecimalField(
        validators=[MinValueValidator(1)],
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )
    picture = models.ImageField(
        upload_to=user_directory_path,
        verbose_name="Product Image",
        null=True,
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    on_moderation = models.BooleanField(default=True)
    average_rating = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        max_digits=2,
        decimal_places=1,
    )
    feedback_counter = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10000)], default=0
    )

    def __str__(self):
        return f"{self.name} - {self.user}"

    def get_absolute_url(self):
        return reverse(
            "goods:product-card",
            kwargs={
                "slug_category": self.category.slug,
                "product_id": self.pk,
            },
        )

goods/forms.py
from django import forms
from django.core.validators import MinValueValidator
from django.forms import TextInput, Select, FileInput, Textarea

from .models import Product

CURRENCY_CHOICES = [
    ("EURO", "Euro"),
    ("USD", "Dollars"),
]

SEARCH_FILTERS = [
    ("NEW", "the newest"),
    ("OLD", "the oldest"),
    ("CHEAP", "cheap first"),
    ("EXPENSIVE", "expensive first"),
    ("RATING", "by rating"),
]

card_widgets = {
    "category": Select(
        attrs={
            "class": "form-select",
        }
    ),
    "subcategory": Select(
        attrs={
            "class": "form-select",
        }
    ),
    "name": TextInput(
        attrs={
            "placeholder": "Product name",
            "class": "form-control",
        }
    ),
    "amount": TextInput(
        attrs={
            "placeholder": "amount",
            "class": "form-control",
        }
    ),
    "price": TextInput(
        attrs={
            "placeholder": "price",
            "class": "form-control",
        }
    ),
    "currency": Select(
        attrs={
            "class": "form-select",
        }
    ),
    "part_number": TextInput(
        attrs={
            "placeholder": "Part number",
            "class": "form-control",
        }
    ),
    "discription": Textarea(
        attrs={
            "placeholder": "Discription",
            "class": "form-control",
            "rows": 5,
        }
    ),
    "picture": FileInput(
        attrs={
            "class": "form-control",
        }
    ),
}


class NewCardForm(forms.ModelForm):
    currency = forms.ChoiceField(
        choices=CURRENCY_CHOICES, widget=card_widgets["currency"]
    )
    price = forms.DecimalField(
        validators=[MinValueValidator(1)],
        max_digits=10,
        decimal_places=2,
        widget=card_widgets["price"],
    )
    field_order = (
        "category",
        "subcategory",
        "name",
        "amount",
        "price",
        "currency",
        "part_number",
        "discription",
        "picture",
    )

    class Meta:
        model = Product
        fields = (
            "category",
            "subcategory",
            "name",
            "part_number",
            "discription",
            "amount",
            "picture",
        )
        widgets = card_widgets

    def __init__(self, *args, **kwargs):
        super(NewCardForm, self).__init__(*args, **kwargs)
        self.fields["picture"].required = False


class SearchFiltersForm(forms.Form):
    search_filter = forms.ChoiceField(choices=SEARCH_FILTERS)
    on_stock = forms.BooleanField(required=False)
    currency = forms.ChoiceField(choices=CURRENCY_CHOICES)

goods/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from .models import *
from .forms import *
from cart.forms import AddToCartForm
from django.views.generic import View, ListView, DeleteView, DetailView


class MarketPage(ListView):
    model = Category
    template_name = "goods/market.html"
    context_object_name = "categories"


class ProductCard(DetailView):
    model = Product
    template_name = "goods/product_card.html"
    pk_url_kwarg = "product_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart_form"] = AddToCartForm()
        if "currency" in self.request.COOKIES:
            context["currency"] = self.request.COOKIES.get("currency")
        else:
            context["currency"] = "EURO"
        return context


@login_required
def create_product_card(request):
    if request.method == "POST":
        card_form = NewCardForm(request.POST, request.FILES)
        if card_form.is_valid():
            product = card_form.save(commit=False)
            product.user = request.user
            currency_rate = float(CurrencyRate.objects.latest().Euro_to_Usd)
            price = float(request.POST["price"])
            currency = request.POST["currency"]
            if currency == "USD":
                product.price_usd = price
                product.price_euro = price / currency_rate
            else:
                product.price_usd = price * currency_rate
                product.price_euro = price
            product.average_rating = 0
            product.feedback_counter = 0
            product.save()
            return HttpResponseRedirect(f"{product.get_absolute_url()}")
    else:
        card_form = NewCardForm()
    return render(
        request,
        "goods/new_product_card.html",
        context={
            "card_form": card_form,
        },
    )


order_param_dict = {
    "NEW": "-created",
    "OLD": "created",
    "CHEAP": "price_euro",
    "EXPENSIVE": "-price_euro",
    "RATING": "-average_rating",
}


def category(request, slug_category: str, slug_subcategory=None):
    current_category = get_object_or_404(Category, slug=slug_category)

    if "currency" in request.COOKIES:
        currency = request.COOKIES.get("currency")
    else:
        currency = "EURO"

    if request.GET:
        currency = request.GET["currency"]
        new_param = request.GET["search_filter"]
        order_param = order_param_dict[new_param]
        if "on_stock" in request.GET:
            products = Product.objects.filter(
                category=current_category.id, amount__gt=0, on_moderation=False
            ).order_by(order_param)
        else:
            products = Product.objects.filter(
                category=current_category.id, amount__gt=-1, on_moderation=False
            ).order_by(order_param)
    else:
        products = Product.objects.filter(
            category=current_category.id, on_moderation=False
        ).order_by("-created")

    add_to_cart_form = AddToCartForm()

    current_subcategory = None
    if slug_subcategory:
        current_subcategory = get_object_or_404(Subcategory, slug=slug_subcategory)
        products = products.filter(subcategory=current_subcategory)

    new_request = request.GET.copy()
    new_request["currency"] = currency
    filters_form = SearchFiltersForm(new_request)

    products_list = products
    paginator = Paginator(products_list, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    response = render(
        request,
        "goods/category.html",
        context={
            "current_category": current_category,
            "products": products,
            "cart_form": add_to_cart_form,
            "filters_form": filters_form,
            "current_subcategory": current_subcategory,
            "currency": currency,
            "page_obj": page_obj,
        },
    )

    if request.GET:
        response.set_cookie("currency", currency)
    return response


@login_required
def products_on_moderation(request):
    products = Product.objects.filter(on_moderation=True)
    return render(
        request,
        "goods/ad_moderation.html",
        context={
            "products": products,
        },
    )


def search(request):
    search = request.GET.get("search", "")
    if search or request.GET:
        if "currency" in request.GET:
            currency = request.GET["currency"]
        else:
            currency = "EURO"
        if "search_filter" in request.GET:
            new_param = request.GET["search_filter"]
            order_param = order_param_dict[new_param]
        else:
            order_param = "-created"
        add_to_cart_form = AddToCartForm()
        filters_form = SearchFiltersForm(request.GET)
        if "on_stock" in request.GET:
            products = Product.objects.filter(
                amount__gt=0, on_moderation=False
            ).order_by(order_param)
        else:
            products = Product.objects.filter(
                amount__gt=-1, on_moderation=False
            ).order_by(order_param)

        products_list = products
        paginator = Paginator(products_list, 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(
            request,
            "goods/search.html",
            context={
                "page_obj": page_obj,
                "currency": currency,
                "filters_form": filters_form,
                "add_to_cart_form": add_to_cart_form,
            },
        )
    return HttpResponseRedirect("/")


class RemoveProductOnModeration(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("goods:moderation")


class ApproveProductModeration(View):
    model = Product

    def post(self, request, pk):
        self.model.objects.filter(pk=pk).update(on_moderation=False)
        return HttpResponseRedirect(reverse_lazy("goods:moderation"))

goods/templates/goods/ad_moderation.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Moderation{% endblock %}


{% block content %}
<section>
    <div class="container mt-2 mb-3">
        <div class="d-flex justify-content-center">
            <h1>Product cards on moderation</h1>
        </div>
        <div class="row">
            {% for product in products %}
            {% if product.on_moderation %}
            <div class="col-md-4">
                <div class="product">
                    <div class="product-image">
                        <img src="{{product.picture.url}}" alt="{{ product.name }}" width="300" height="200">
                    </div>
                    <div class="info">
                        <a href="{{ product.get_absolute_url }}"><h3>{{ product.name }}</h3></a>
                        <div class="cat"><b>Category</b> <small>{{ product.category }}</small></div>
                        <div class="subcat"><b>Subcategory</b> <small>{{ product.subcategory }}</small></div>
                        <div class="info-box">
                            <span class="amount">{{ product.amount }} qty available</span>
                        </div>
                        <div class="info-box">
                            {% if currency == 'USD' %}
                            <span class="price">{{ product.price_usd }} <small>$</small></span>
                            {% else %}
                            <span class="price">{{ product.price_euro }} <small>€</small></span>
                            {% endif %}
                        <div class="moderation-block btn-group" role="group">
                             <form method="POST" action="{% url 'goods:moderation-remove' product.pk %}">
                                 {% csrf_token %}
                                 <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            <form method="POST" action="{% url 'goods:moderation-approve' product.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Approve</button>
                            </form>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}

goods/templates/goods/category.html
{% extends 'base.html' %}
{% load static %}
{% load goods_tags %}
{% load feedback_tags %}
{% block title %}{{ category.name }}{% endblock %}


{% block content %}
<table class="category-table">
        <tbody>
            <tr>
                {% show_sidebar category_selected=current_category %}
                <td class="categories-content" valign="top">
                    <div class="container">
                        {% if current_subcategory %}
                            <h1>{{ current_subcategory }}</h1>
                        {% endif %}
                        {% if products %}
                        <div class="container mt-2 mb-3">
                            <form class="filters" method="get">
                                {% for field in filters_form %}
                                    {{ field.label_tag }}
                                    {{ field }}
                                {% endfor %}
                                <label for="page">Page</label>
                                <select name="page">
                                {% for page in page_obj.paginator.page_range %}
                                    {% if page_obj.number == page %}
                                    <option value="{{page}}" selected>{{page}}</option>
                                    {% else %}
                                    <option value="{{page}}">{{page}}</option>
                                    {% endif %}
                                {% endfor %}
                                </select>
                                <button class="search-btn" type="submit"><ion-icon name="search-circle"></ion-icon></button>
                            </form>
                        </div>
                        <div class="row">
                            {% for product in page_obj %}
                            {% if not product.on_moderation %}
                            <div class="col-md-4">
                                <div class="product">
                                    <div class="product-image">
                                        <img src="{{product.picture.url}}" alt="{{ product.name }}" width="300" height="200">
                                    </div>
                                    <div class="info">
                                        <a href="{{ product.get_absolute_url }}"><h3>{{ product.name }}</h3></a>
                                        <div class="info-box">
                                            {% show_feedback_stars average_rating=product.average_rating show_counter=True counter=product.feedback_counter %}
                                            <span class="amount">{{ product.amount }} qty available</span>
                                        </div>
                                        <div class="info-box">
                                            {% if currency == 'USD' %}
                                            <span class="price">{{ product.price_usd }} <small>$</small></span>
                                            {% else %}
                                            <span class="price">{{ product.price_euro }} <small>€</small></span>
                                            {% endif %}

                                            {% if user.profile.user_type == 'Customer' and product.amount > 0 %}
                                            <div class="add_to_cart_form">
                                                <form class="d-flex justify-content-between align-items-center" action="{% url 'cart:add_to_cart' product.pk %}" method="post" target="_blank">
                                                    {% csrf_token %}
                                                    <a class="btn btn-link px-2"
                                                        onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                        <ion-icon name="remove-outline"></ion-icon>
                                                    </a>
                                                    {% for field in cart_form %}
                                                    {{ field }}
                                                    {% endfor %}
                                                    <a class="btn btn-link px-2"
                                                        onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                                        <ion-icon name="add-outline"></ion-icon>
                                                    </a>
                                                    <button  class="add-to-cart"><ion-icon name="cart"></ion-icon></button>
                                                </form>
                                            </div>
                                            {% else %}
                                            <div></div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                <div class="container mt-3 availability">
                    <h2>No products available</h2>
                    <ion-icon class='availability-icon' name="sad-outline"></ion-icon>
                </div>
                {% endif %}
                </td>
            </tr>
        </tbody>
    </table>

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}

goods/templates/goods/market.html
{% extends 'base.html' %}

{% block title %}Market{% endblock %}


{% block content %}
    <div class="container my-5">
        <div class="row row-cols-1 row-cols-md2 row-cols-lg-5 g-3">
        {% for category in categories %}
            <div class="col">
                <div class="category-card">

                    <a href="{{ category.get_absolute_url }}">
                    <img class='category-img' src="{{category.picture.url}}" alt="">
                        <h1 class="cat-name">{{ category.name }}</h1></a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

goods/templates/goods/new_product_card.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New product card{% endblock %}

{% block content %}
<section class="new-product-card">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7 col-lg-5">
                <div class="login-wrap p-4 p-md-5">
                    <div class="d-flex align-items-center justify-content-center">
                        <i class="fa-solid fa-steering-wheel"></i>
                    </div>
                    <h3 class="text-center mb-4">Create a new product card</h3>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ card_form.non_field_errors }}
                        {% for field in card_form %}
                            <div class="form-group mb-3">
                                {{ field.label }}:
                                {{ field }}
                                {{ field.errors }}
                            </div>
                        {% endfor %}
                        <div class="form-group mb-2">
                            <button class="form-control btn btn-primary rounded submit px-3" type="submit">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://kit.fontawesome.com/26fc0dada0.js" crossorigin="anonymous"></script>
{% endblock %}

goods/templates/goods/product_card.html
{% extends 'base.html' %}
{% load static %}
{% load feedback_tags %}
{% block title %}{{ product.name }}{% endblock %}


{% block content %}
<div class="container product-card mt-3">

    <div class="product-content">
        {% if product.on_moderation %}
        <div class="moderation-block">
            Your product card was submitted and will be reviewed by a moderator before
            being visible to all users. This post is currently awaiting for a moderator to review.
        </div>
        {% endif %}

        <div class="row">
            <div class="product-picture col-8">
                <img src="{{product.picture.url}}" alt="Product Card">
            </div>
            <div class="info col-4">
                <h1 class="fs-3 lh-1">{{ product.name }}</h1>
                <span class="fw-semibold text-muted"><small>Part number</small> {{ product.part_number }}</span>
                <div class="product-user mb-3">
                    Owner: <a href="#">{{ product.user }}</a>
                </div>
                {% if product.subcategory %}
                <div class="product-subcat">Subcategory:
                    <span class="fw-bolder">{{ product.subcategory }}</span>
                </div>
                {% endif %}
                <div class="product-amount">Amount available:
                    <span class="fw-bolder">{{ product.amount }}</span>
                </div>
                <div class="product-price">Price:
                    {% if currency == 'EURO' %}
                    <span class="fw-bolder">{{ product.price_euro }} €</span>
                    {% else %}
                    <span class="fw-bolder">{{ product.price_usd }} $</span>
                    {% endif %}
                </div>
                <div class="product-feedbacks mt-2">
                    <a href="#feedbacks">{% show_feedback_stars average_rating=product.average_rating show_counter=True counter=product.feedback_counter %}</a>
                </div>
                <div class="product-form mt-2">
                    {% if product.amount > 0 %}
                <div class="add_to_cart_form">
                    <form class="d-flex  align-items-center" action="{% url 'cart:add_to_cart' product.pk %}" method="post" target="_blank">
                        {% csrf_token %}
                        <a class="btn btn-link px-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                            <ion-icon name="remove-outline"></ion-icon>
                        </a>
                        {% for field in cart_form %}
                        {{ field }}
                        {% endfor %}
                        <a class="btn btn-link px-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                            <ion-icon name="add-outline"></ion-icon>
                        </a>
                        <button class="add-to-cart"><ion-icon name="cart"></ion-icon></button>
                    </form>
                </div>
                    {% endif %}
            </div>
        </div>

        <div class="discription mt-3">
            <span class="fw-semibold text-muted"><small>Created</small> {{ product.created }}</span>
            <div class="fw-semibold">Discription:</div>
            <div class="lh-1"> {{ product.discription|linebreaks }}</div>
        </div>
    </div>


    <div class="mt-3 feedback">
        {% if request.user.profile == 'CUSTOMER' %}
        <div class="review">
            <div class="fs-6 fw-semibold">Write a Review</div>
            {% show_feedback_form product_pk=product.pk  %}
        </div>
        {% endif %}
        <div class="mt-3 feedbacks">
            <h3>Customer reviews</h3>
            <div class="rating-info">
                {% show_feedback_stars average_rating=product.average_rating %}
                <span><small>{{ product.feedback_counter}} total ratings</small></span>
            </div>
            <br>
            <a name="feedbacks"></a>
            {% for feedback in product.feedback.all %}
                <div class="one-feedback-block">
                    <div class="feedback-username">
                        <span class="fw-semibold text-muted"><small>{{ feedback.user }}</small></span>
                    </div>
                    <div class="feedback-rating">
                        {% show_feedback_stars average_rating=feedback.rating %}
                    </div>
                    <div class="text-muted"><small>Reviewed {{ feedback.date }}</small></div>
                    <div class="feedback-data fst-italic lh-1">
                        {{ feedback.text|linebreaks }}
                    </div>

                    {% if feedback.user == request.user or request.user.is_staff %}
                    <a class="btn btn-danger" href="{% url 'feedback:remove_feedback' feedback.pk %}">delete</a>
                    {% endif %}
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</div>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}