Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "AutoMarket"
admin.site.index_title = "Admin panel"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("market/", include(("goods.urls", "goods"), namespace="goods")),
    path("cart/", include(("cart.urls", "cart"), namespace="cart")),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("", include("users.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>", add_to_shopping_cart, name="add_to_cart"),
    path("remove/<int:product_id>", remove_from_cart, name="remove_from_cart"),
    path("orders-history", OrdersHistory.as_view(), name="orders-history"),
    path("orders-history/<int:order_pk>", order_info, name="order"),
    path("orders-history/<int:pk>/remove/", RemoveOrder.as_view(), name="remove-order"),
]

goods/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", MarketPage.as_view(), name="market"),
    path("search", search, name="search"),
    path("create", create_product_card, name="create-card"),
    path("moderation", products_on_moderation, name="moderation"),
    path(
        "moderation/remove/<int:pk>",
        RemoveProductOnModeration.as_view(),
        name="moderation-remove",
    ),
    path(
        "moderation/approve/<int:pk>",
        ApproveProductModeration.as_view(),
        name="moderation-approve",
    ),
    path("<slug:slug_category>", category, name="category-detail"),
    path(
        "<slug:slug_category>/<int:product_id>",
        ProductCard.as_view(),
        name="product-card",
    ),
    path(
        "<slug:slug_category>/<slug:slug_subcategory>", category, name="category-detail"
    ),
]

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'libs/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/bootstrap-grid.min.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'pictures/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'pictures/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'pictures/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'pictures/favicon/site.webmanifest' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    {% block link %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-logo" href="{% url 'index' %}">AutoLand</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
                {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'goods:moderation' %}">Moderation</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'goods:market' %}">Market</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ user.profile.user_type }}, {{ user.username }}
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.profile.user_type == 'Customer' %}
                        <li><a class="dropdown-item" href="{% url 'cart:cart_detail' %}">Cart</a></li>
                        <li><a class="dropdown-item" href="{% url 'cart:orders-history' %}">Purchase history</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'my_products' %}">My products</a></li>
                        <li><a class="dropdown-item" href="{% url 'goods:create-card' %}">New product card</a></li>
                        <li><a class="dropdown-item" href="#">Sales report</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Exit</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'goods:market' %}">Market</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_new' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sign_up' %}">Sign Up</a>
                </li>
            {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url 'goods:search' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-dark" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>


{% block content %}{% endblock %}
</body>
</html>